[project]
name = "db-backup-management"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "SQLAlchemy >= 2.0.43",
    "PyMySQL >= 1.1.2"
]
